# SPDX-License-Identifier: MIT
#
# Apply patches/mfc_dace.patch to a MIRROR of the source tree under the build directory.
#
#   cmake -DSRC=<source root> -DMIRROR=<build-dir mirror> -DPATCH=<patch file> -P dace_apply_patch.cmake
#
# WHY A MIRROR AND NOT IN PLACE.  The patch carries the dispatch call sites -- the `if (predicate)
# call s_dace_*(...) else <stock loops>` regions that make the DaCe kernels reachable.  Applying it
# in place would (a) dirty the working tree on every configure, so `MFC_DACE=OFF` would no longer be
# a pristine upstream checkout; (b) not be idempotent, because a re-configure re-runs it on an
# already-patched file; and (c) feed the patched text to every generator, which reads the source
# tree directly.
#
# WHY ONE COMMAND FOR THE WHOLE PATCH.  `src/common/*.fpp` are globbed into four targets, so a
# per-file `add_custom_command(OUTPUT ...)` would be declared by several targets and CMake would
# error with "multiple rules generate <path>".  This script patches the whole set in one go.
#
# WHY --fuzz=0 AND A HARD FAILURE.  Every other gate in this project is bit-identity, and bit-
# identity is SATISFIED BY THE STOCK LOOPS.  So a patch that quietly fails to apply would turn every
# dispatch off and every gate would still pass.  The failure has to be a build error.

if(NOT DEFINED SRC OR NOT DEFINED MIRROR OR NOT DEFINED PATCH)
    message(FATAL_ERROR "dace_apply_patch: SRC, MIRROR and PATCH are all required")
endif()
if(NOT EXISTS "${PATCH}")
    message(FATAL_ERROR
        "MFC_DACE: the dispatch patch is missing:\n  ${PATCH}\n"
        "It is generated by the porting scripts from the fork's source diff; see patches/README.md.")
endif()

# Rebuild the mirror from scratch: a re-run cannot double-apply, and a file removed from the patch
# cannot linger.
file(REMOVE_RECURSE "${MIRROR}")
file(MAKE_DIRECTORY "${MIRROR}")

# The files the patch touches, read FROM THE PATCH so the list cannot drift from its content.
file(STRINGS "${PATCH}" _headers REGEX "^\\+\\+\\+ b/")
set(_files "")
foreach(_h ${_headers})
    string(REGEX REPLACE "^\\+\\+\\+ b/" "" _rel "${_h}")
    string(REGEX REPLACE "\t.*$" "" _rel "${_rel}")
    list(APPEND _files "${_rel}")
endforeach()
if(_files STREQUAL "")
    message(FATAL_ERROR "MFC_DACE: no '+++ b/' headers in ${PATCH} -- is it a unified diff?")
endif()

# THE PATCH MUST NOT CREATE FILES.  HANDLE_SOURCES globs the SOURCE tree, so a file that exists
# only in the mirror is never added to the target -- the patch would appear to apply and the build
# would fail much later with an undefined symbol, far from the cause.  New files (the shims, the
# runtime helpers) are ADDED to the repository, not patched into it.  Checked here so the failure
# is immediate and says what to do.
set(_copied 0)
foreach(_rel ${_files})
    if(NOT EXISTS "${SRC}/${_rel}")
        message(FATAL_ERROR
            "MFC_DACE: the dispatch patch CREATES ${_rel}, which this build cannot pick up:\n"
            "HANDLE_SOURCES globs the source tree, so a file present only in the mirror is never\n"
            "compiled.  Add it to the repository instead of to the patch.")
    endif()
    get_filename_component(_dir "${MIRROR}/${_rel}" DIRECTORY)
    file(MAKE_DIRECTORY "${_dir}")
    configure_file("${SRC}/${_rel}" "${MIRROR}/${_rel}" COPYONLY)
    math(EXPR _copied "${_copied} + 1")
endforeach()

find_program(PATCH_EXECUTABLE NAMES patch REQUIRED)
execute_process(
    COMMAND "${PATCH_EXECUTABLE}" -p1 -N --fuzz=0 -i "${PATCH}"
    WORKING_DIRECTORY "${MIRROR}"
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE _err)

if(NOT _rc EQUAL 0)
    message(FATAL_ERROR
        "MFC_DACE: the dispatch patch did not apply (patch exit ${_rc}).\n"
        "--- stdout ---\n${_out}\n--- stderr ---\n${_err}\n"
        "This is a hard error on purpose.  If it were ignored the build would silently compile the\n"
        "STOCK loops and every bit-identity gate would still pass -- the dispatches would simply be\n"
        "off.  Fix by regenerating patches/mfc_dace.patch against the source the build is using.")
endif()

file(WRITE "${MIRROR}/.patched" "ok\n")
message(STATUS "MFC_DACE: dispatch patch applied to ${MIRROR} (${_copied} files copied, "
               "${_files} in the patch)")
